// scenarios.js
const scenarios = [
  {
    nom: "La démonstratrice en produits de beauté",
    id: 1,
    pitch: "{prenom} est démonstratrice pour une marque très luxueuse. Elle vient chez un couple pour un nouveau produit révolutionnaire. {prenom} explique qu'elle doit s'isoler avec monsieur pour récolter sa semence. Seuls, elle le caressera et le sucera en lui expliquant qu'une fois qu'il aura éjaculé, elle plongera son visage dans les flaques de sperme pour s'en recouvrir.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La cliente au fantasme inavouable", 
    id: 2,
    pitch: "{prenom} engage un prostitué à qui elle demande de jouer le rôle de jouet sexuel obéissant. Elle va le branler et le sucer tout en lui expliquant ce qu'elle attend de lui. Elle a toujours voulu réaliser ce fantasme mais son mari refuse. Elle veut qu'il jouisse dans ou sur sa chatte puis s'accroupir au-dessus du visage du prostitué qui devra la faire jouir en léchant son propre sperme.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 5
  },
  {
    nom: "La femme de ménage consciencieuse",
    id: 3,
    pitch: "Madame lui a demandé de bien s'occuper de la maison et de son mari pendant son absence. Aussi, {prenom} s'applique à bien faire son travail. Tous les matins, elle se rend dans la suite parentale et, sans un mot, branle consciencieusement monsieur qui la regarde à moitié endormi. Cela peut prendre du temps, aussi elle est patiente et par moment dépose légèrement ses lèvres sur le gland bombé pour le téter. Elle ne fait pas ça par plaisir, mais par professionnalisme. Pour faire venir la jouissance, elle l'excite en lui disant qu'elle nettoiera la semence avec sa bouche.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 3
  },
  {
    nom: "La baby-sitter voleuse",
    id: 4,
    pitch: "{prenom} a merdé. Elle n'a pas pu s'empêcher de voler de l'argent chez le papa solo qui lui avait demandé de garder son bébé. Il l'a pris sur le fait et lui demande de rendre l'argent et de ne plus jamais revenir. {prenom} est vraiment désolée et est prête à donner d'elle-même pour se faire pardonner et garder son boulot. Elle se déshabille en le regardant avec des yeux aguicheurs et commence à déboutonner son pantalon. À genoux, elle le branle, puis le suce en le regardant dans les yeux et lui propose d'éjaculer sur sa chatte, son anus ou dans la bouche pour qu'elle avale tout.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 4
  },
  {
    nom: "La receveuse de sperme",
    id: 5,
    pitch: "{prenom} a choisi son donneur et s'apprête à recevoir son sperme. Elle ne le connait pas, mais il correspond à tout ce qu'elle veut pour son enfant. Ils appliquent alors la procédure décrite par le personnel de la clinique : elle est nue, allongée sur le lit, les jambes écartées. Lui s'installe à genoux au-dessus de son visage, le sexe à sa verticale et le pénis érigé vers le ventre de {prenom}. La procédure insiste bien sur le fait qu'elle doit masturber l'inconnu elle-même tout en s'occupant de ses bourses. Pour que le sperme soit de la meilleure qualité, elle doit les caresser doucement, les lécher, les sucer. Quand il éjaculera, il essaiera de viser le plus loin possible pour atteindre la vulve, et {prenom} récupérera le sperme restant sur son ventre pour se l'introduire elle-même.",
    minPresentation: 5,
    minCaresses: 2,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 3,
    minSperme: 1
  },
  {
    nom: "L'hôtesse de luxe",
    id: 5,
    pitch: "{prenom} est hôtesse dans un établissement de luxe. Son rôle : obtenir la meilleure note de satisfaction client. Cela tombe bien, elle a très envie de satisfaire ce client-ci. Après lui avoir servi de guide et d'assistante toute la journée, elle se présente le soir à la porte de sa chambre en tenue beaucoup plus sexy. Il n'a pas besoin de lui demander ce qu'il veut, il a déjà rempli le formulaire requis et elle sait très bien ce qui le fera jouir. Elle à genoux, toujours habillée, lui debout, totalement nu. Elle le caresse et le suce doucement, lentement, jusqu'à ce qu'il soit bien tendu. Là, elle commencera à s'enfoncer la queue du client dans la gorge, de plus en plus profond, en respirant lentement et en le regardant dans les yeux. Puis elle lui dira \"c'est le moment, monsieur, de me baiser la bouche et de vous vider sur mon visage\" et elle n'aura plus qu'à le laisser s'en occuper.",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La fan d'un auteur érotique",
    id: 6,
    pitch: "{prenom} n'en croit pas ses yeux. Elle a devant elle la queue dure de son auteur fétiche. Lui, l'auteur érotique à succès. Elle a tout lu de lui, elle sait tout de sa vie, elle sait exactement ce qu'il faut qu'elle fasse pour le faire jouir. Et elle a bien l'intention de sentir couler son sperme sur sa peau ou dans sa bouche. Elle sait par exemple qu'il adore les gros seins comme les siens. Elle sait aussi qu'il aime qu'on lui caresse les couilles et l'entrée de l'anus. Comme elle adore ça, elle va bien lui sucer les couilles tout en le branlant. Il va pouvoir jouir sur ses gros seins et peut-être qu'elle récupérera un peu du sperme sacré pour le gouter d'un doigt gourmand.",
    minPresentation: 3,
    minCaresses: 4,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 2,
    minSperme: 4
  },
  {
    nom: "L'exorciste charnelle",
    id: 7,
    pitch: "{prenom} a un cas particulièrement délicat aujourd'hui. Un rare et délicat \"Démon de la Lune\". Elle sait ce qu'elle doit faire pour sortir le pauvre homme de sa torpeur éternel. Elle demande à sa femme de les laisser seuls. Là, elle ordonne à l'homme de se mettre nu et à quatre pattes. Il ne sait plus faire que ça : obéir docilement. Il n'a plus de libre arbitre, le démon le place dans une sorte de torpeur hypnotique. Elle place un récipient entre ses jambes, directement sous son pénis et commence à le traire. Au début doucement, puis avec vigueur. Après de longue minutes qui lui font mal au bras, elle commence le rituel. Elle crache sur son anus et le lèche doucement pour l'humidifier, puis le pénètre d'un doigt délicat. C'est ainsi que le démon sera expulsé dans le récipient.",
    minPresentation: 1,
    minCaresses: 5,
    minExploration: 5,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La modèle d'artiste excentrique",
    id: 8,
    pitch: "{prenom} a beaucoup de chance. Elle a été choisie parmi de nombreuses autres femmes pour être la modèle d'un grand artiste photographe reconnu mondialement. Ses collections sont toujours aussi non-conformistes, c'est ce qui fait sa force et sa renommée. Elle est prête. Il lui demande de se déshabiller et lui explique que sa nouvelle collection sera appelée \"masque sur beauté\". Il se met nu à son tour, {prenom} est embarassée, surtout quand il lui demande si elle est d'accord pour recevoir sa semence, son matériau principal, sur le visage. C'est un acte purement professionnel, dit-il. Elle accepte et il l'encourage à l'aider à obtenir l'effet voulu puisqu'il a les deux mains prises par son art.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La spécialiste du sommeil",
    id: 9,
    pitch: "C'est une méthode révolutionnaire que {prénom} propose à ce patient pour soigner ses insomnies. Elle lui avoue que c'est encore en cours d'expérimentation et lui propose de la tester gratuitement. Le principe repose sur la production de mélatonine, l'hormone du sommeil générée par l'orgasme masculin. Il s'agit donc de mettre le patient dans un lit confortable et de s'occuper de le faire éjaculer tandis qu'il chercher le sommeil doucement. Tout est affaire de doigté et de subtilité. Des doigts délicats, une bouche légère, une langue habile et déterminée. Alors qu'il a les yeux fermés, elle lui explique comment marche sa méthode et surtout comment ça va se terminer. En effet, ce protocol est bien plus efficace si, après avoir éjaculé, le patient ingère un peu de son sperme. Elle lui explique donc qu'elle en récupérera avec sa bouche pour venir lui faire un baiser de bonne nuit.",
    minPresentation: 4,
    minCaresses: 2 ,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 5
  },
  {
    nom: "L'impératrice tyrannique",
    id: 10,
    pitch: "{prenom} ne veut pas d'amants et encore moins d'époux. Elle continuera à diriger cet empire seule. Elle a juste besoin d'assurer une descendance, une fille, pour qu'elle puisse reprendre sa suite. Elle ne veut donc pas d'amants, elle veut juste un esclave et sa semence. Elle en a sélectionné un nouveau, en espérant qu'il soit moins incapable que les autres. Il s'allonge et elle vient directement placer sa chatte sur sa bouche et se frotte contre lui. Elle lui attrape la queue et la fait durcir. Elle prend son temps, elle adore ça. Elle le branle, le suce, bave abondemment sur cette queue pathétique qui veut probablement la pénétrer mais qui ne le fera jamais puisqu'il n'en est pas digne. Elle veut juste qu'il abandonne sa semence. Elle se frottera la chatte sur son sexe suppliant, mais sans jamais le faire entrer. Elle le fera jouir par tous les moyens s'il le faut.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 3,
    minSperme: 1
  },
  {
    nom: "La directrice d'hôtel",
    id: 11,
    pitch: "{prenom} a un pépin ce soir, l'une de ses filles est absente et elle n'a personne pour la remplacer. Surtout qu'elle tient à ce client. Elle décide donc de prendre sa place au pied levé. Ça ne doit pas être bien compliqué, si ces idiotes peuvent le faire, elle aussi. Le client parait un peu surpris de la voir, mais se met à l'aise très rapidement en se déshabillant. {prenom} fait mine de rien, professionnelle, mais elle commence à regretter de s'être mis dans cet embarras quand le client lui explique qu'il a l'habitude de se branler entre les seins de son habituée jusqu'à les recouvrir de son sperme et de la regarder nettoyer avec la langue...",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 3
  },
  {
    nom: "La meilleure amie insistante",
    id: 12,
    pitch: "{prenom} a besoin de son meilleur ami pour lui demander une faveur délicate. Elle a suffisamment insisté pour qu'il finisse par accepter. Non pas qu'il n'en ait pas envie, mais parce qu'il a peur que ça change leur relation. Pourtant, il a fini par se laisser tenter. {prenom} voudrait faire plaisir à son mec en lui faisant une gorge profonde parce qu'elle s'est vanté être experte en la matière, ce qui est complètement faux. Elle aimerait donc s'entrainer. Ses règles : elle reste habillée et surtout il ne touche rien, elle a juste besoin de sa bite. S'il jouit, ce sera au fond de sa gorge. Peut-être qu'alors elle avalera, elle verra.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 4,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La patronne autoritaire",
    id: 13,
    pitch: "{prenom} dirige sa boite d'une main de fer. Ses employés le savent et ceux qui veulent rester se soumettent à ses caprices. Certains se soumettent même à ses désirs sexuels. C'est le cas de l'homme qui se trouve debout face à elle, nu, dans son bureau. Elle veut juste le faire jouir pour l'humilier, pas même pour son plaisir. Elle va le branler, le sucer, le faire jouir sur ses gros seins et pour finir, le faire nettoyer lui-même son sperme.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 5
  },
  {
    nom: "Sorcière en quête de puissance",
    id: 14,
    pitch: "{prenom} est une sorcière et pour combattre le mal qui étend ses racines partout dans le monde, elle a besoin de puissance. Elle a lu dans un ancien grimoire que la semence de l'homme le plus idiot du village pouvait devenir le plus efficace des breuvages. C'est pourquoi elle le pompe avec avidité, jusqu'à ce qu'il jouisse au fond de sa gorge et qu'elle se régale de son nectar.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 4,
    minSperme: 4
  },
  {
    nom: "La tenancière d'un salon de thé d'exception",
    id: 15,
    pitch: "C'est l'heure de la récolte. Le salon de thé de {prenom} est connu dans tout le royaume pour la saveur délicate de ses thés et tisanes. Et tout ça, grâce à un ingrédient dont elle a le secret de mère en fille. Elle paye un employé à plein temps uniquement pour qu'il s'entretienne, suive un régime alimentaire strict et lui donne secrètement une dose quotidienne de sa semence. Pour l'extraire, une petite formule magique sur ses couilles, sans oublier de les masser, les huiler, les lécher et les sucer longuement. En pratiquant correctement, avec un bon coup de poignet sur le manche, on peut récupérer une crème idéale pour ses concoctions.",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'étudiante en biologie",
    id: 16,
    pitch: "{prenom} est en retard pour son rapport de fin d'année. Son professeur lui propose de l'aider et elle le prend au mot. Il n'avait peut-être pas conscience qu'il lui manquait la partie sur l'anatomie masculine et son orgasme. En acceptant, il ne pensait pas terminer assis face à son étudiante, seins nus, la queue entre ses mains, à devoir lui expliquer le fonctionnement de son pénis et des différentes intéractions nécessaires à son éjaculation. Mais quand elle a proposé de le laisser jouir sur ses gros seins, il a étrangement accepté sans discuter.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 2
  },
  {
    nom: "L'épouse partageuse",
    id: 17,
    pitch: "{prenom} a décidé d'offir à son mari un cadeau un peu particulier. Elle lui bande les yeux et lui demande de s'allonger sur un table ou au sol. Là, elle va lui raconter ce qui va se passer à son oreille. Elle a invité une autre femme qui préfère rester anonyme et qui va lui donner du plaisir jusqu'à ce qu'il jouisse.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'enseignante en médecine",
    id: 18,
    pitch: "{prenom} a proposé à son élève préféré des cours du soir pour aborder une notion qui lui semble inconnue : l'orgasme prostatique. Il se prête volontiers à l'expérience et elle prend un ton professoral tout en pratiquant sur lui. Il est à quatre pattes, elle lui doigte délicatement l'anus et le branle en même temps jusqu'à ce qu'il explose.",
    minPresentation: 1,
    minCaresses: 5 ,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "Le rituel de la druidesse",
    id: 19,
    pitch: "{prenom} doit réaliser un rituel délicat afin de soigner un patient. Pour cela, elle devoir extraire son mal de la plus sexuelle des manières. Le procédé est très précis et ne souffre d'aucune inexactitude. Le patient doit se placer à quatre pattes, entièrement nu, tandis qu'elle se glissera entre ses jambes. Elle doit activer son orgasme en caressant son pénis, ses bourses, son anus, ses fesses. Elle a le droit de le masturber ou de légèrement lécher le bout de la queue si elle le peut, mais elle a interdiction de décoller la tête du sol. Le rituel se termine quand le patient éjacule. Elle ne doit surtout pas en avaler une goutte, mais doit le recueillir sur son visage.",
    minPresentation: 1,
    minCaresses: 4,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "Offerte à un inconnu",
    id: 20,
    pitch: "{prenom} a enfin osé sauter le pas. Elle s'est bien apprêtée pour l'occasion, sexy, chaude. Elle doit suivre les instructions de son maitre. Il a décidé de l'offrir à un inconnu. Elle doit garder un masque sur les yeux et s'allonger sur le lit de côté, la bouche accessible par la queue d'un homme à qui elle n'a même jamais dit bonjour. Il viendra et sans un bruit frottera son sexe sur ses joues, sur son nez, sur ses lèvres. Puis il fera pénétrer son gland fébrile et luisant dans la bouche offerte. Il n'aura pas le droit de toucher autre chose que le visage de {prenom}. Juste regarder. Et lui baiser la bouche jusqu'à éjaculer.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La cocue vengeresse",
    id: 21,
    pitch: "{prenom} a découverte que son mec le trompait et elle veut se venger. Elle a rencontré ce type dont elle n'a même pas retenu le prénom mais qui fera parfaitement l'affaire, tant qu'il a une bite opérationnelle. Elle n'a jamais voulu faire une éjaculation faciale avec son ex et il lui a souvent reproché. Alors même si ça la dégoute un peu, elle va laisser cet inconnu lui jouir sur son beau visage et ses gros seins pour lui envoyer une photo qu'il n'est pas prêt d'oublier : elle, couverte de sperme d'un autre homme, un doigt sur ses lèvres comme pour en avaler un peu.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "Le stage à la dure",
    id: 22,
    pitch: "{prenom} a pris un jeune stagiaire très mignon pour faire la vente dans sa boutique et elle lui a fait croire que pour obtenir une bonne note il devait passer un test important. Debout derrière le comptoir (accoudé au bar par exemple), il devra réussir à rester stoïc et ne pas révéler à la clientèle ce qu'il se passe en-dessous. {prenom} est à genoux, la queue du stagiaire dans la bouche et se l'enfonce autant qu'elle le peut. Elle lui masse les couilles et lui caresse le petit trou pour augmenter son plaisir et tenter de le faire défaillir. Quand il jouit, elle le laisse venir sur ses habits.",
    minPresentation: 1,
    minCaresses: 4,
    minExploration: 3,
    minOral: 4,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La thérapeute tantrique",
    id: 23,
    pitch: "{prenom} est thérapeute tantrique. Elle a souvent des hommes très riches et très influents qui viennent découvrir des plaisirs et une relaxation inhabituels. Elle fait parler ses hommes de leur tracas du quotidien tout en manipulant leur queue de ses mains expertes. Elle connait les zones érogènes par coeur : un petit coup de langue par-ci, un doigt fureteur par-là, des massages doux et délicats, une parole rassurante, pour une éjaculation garantie.",
    minPresentation: 4,
    minCaresses: 5,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La belle maudite",
    id: 24,
    pitch: "{prenom} est endormie depuis des années suite à une malédiction terrible. Ce qui la sortira de ce long sommeil ? Le sperme d'un prince sur son visage d'ange.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "Le jeu truqué",
    id: 25,
    pitch: "{prenom} est ravie, son plan a marché comme elle le voulait : inviter le mec sur lequel elle fantasme mais qui est déjà en couple, organiser une soirée entre potes, faire couler l'alcool, sa meilleure amie qui propose innocemment de jouer à des jeux coquins, encore plus d'alcool, des jeux de plus en plus chauds, et le défi qui tombe au bon moment sur les deux bonnes personnes, comme par hasard. Tous deux doivent s'isoler et ne revenir que lorsqu'il y aura une preuve qu'un rapprochement sexuel a eu lieu. {prenom} joue l'ingénue, mais propose à son crush qui ne sait plus où se mettre que la preuve soit sous forme d'un peu de sperme sur ses lèvres...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La thérapeute de couple",
    id: 26,
    pitch: "{prenom} utilise des méthodes atypiques mais qui donnent des résultats. Lors de cette session, elle va faire la démonstration d'une pratique manuelle et orale pour monsieur. Elle va expliquer les différentes zones à caresser, à lécher, à sucer, en s'y pretant allégremment (sauf les bourses, qu'elle n'aime pas trop lécher). Pour l'éjaculation, elle explique qu'il est possible d'avaler ou de recracher. Et pour donner l'exemple, elle prend tout dans la bouche et propose à madame et monsieur d'y gouter en partageant un baiser avec elle.",
    minPresentation: 1,
    minCaresses: 3,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 5
  },
  {
    nom: "La dermatologue innovante",
    id: 27,
    pitch: "{prenom} propose à son patient un traitement qui pourrait fonctionner pour traiter ses démangeaisons. Il s'agit d'étaler du sperme sur la peau touchée. Elle offre ses services pour s'assurer que ce soit bien fait, et passe donc de la théorie à la pratique en masturbant son patient. Elle insiste bien sur la production de sperme en caressant, léchant et suçant ses couilles jusqu'à ce qu'il se jouisse dessus et qu'elle étale d'un doigt expert la semence sur les zones nécessaires.",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La réalisatrice de film d'auteur",
    id: 28,
    pitch: "{prenom} a un petit budget pour réaliser son film, aussi elle est obligée de faire beaucoup de choses artisanalement. Ainsi, lorsqu'il faut repérer l'acteur qui jouera les scènes de sexe, elle va donner de sa personne pour le choisir. Elle va bien observer sa queue, ses réactions, si tout est bien photogénique. Elle ira même jusqu'à le sucer avec gourmandise pour voir à quoi ressemble la jouissance qui jaillira sur son chemisier.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "The good cop",
    id: 29,
    pitch: "{prenom} a carte blanche pour faire avouer le suspect. Après la brutalité de son partenaire, elle tente une approche plus douce, plus persuasive pour lui faire cracher le morceau. Il est assis à une chaise, les mains attachées dans le dos. Elle lui promet ses seins s'il coopère. Elle lui promet ses mains sur sa queue. Peut-être sa bouche. Peut-être même qu'il pourrait se finir sur ses gros seins. Peut-être...",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "Le Bat-Signal",
    id: 30,
    pitch: "{prenom} est Batwoman. Elle a trouvé un Batman dans cette soirée déguisée. Il a l'air pas mal du tout, même si elle ne le voit pas derrière ce masque ridicule. C'était le signe qu'elle attendait. Elle l'a trainé sur le balcon pour boire et discuter de tout et de rien, jusqu'à ce qu'elle sorte sa question préférée \"Tu veux que je te suce ?\". Il n'a pas refusé. Et c'est ainsi qu'ils se sont retrouvés dans ce cagibi, serrés, lui debout, elle accroupie à lui pomper la queue.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La copine bourrée",
    id: 31,
    pitch: "Comment {prenom} s'est-elle retrouvée à accepter ce défi ? L'alcool, évidemment. Et son excitation, aussi. Il faut dire, le mec de sa copine est plutôt mignon, c'est une occasion en or. Maintenant qu'elle est allongée sous sa queue, lui à quatre pattes, elle dégrise. Sa copine lui rappelle le défi : réussir à faire le jouir sans toucher sa bite avec les doigts. Rien ne l'empêche de toucher autre chose. {prenom} se rajoute intérieurement une contrainte : ne pas salir ses habits, elle aurait vraiment dû se déshabiller.",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "L'assaisonnement royal",
    id: 32,
    pitch: "{prenom} aime son royaume, mais elle aime surtout diriger. Diriger des hommes, les voir ramper à ses pieds et faire tout ce qu'elle désire. Le soir, seule à sa table, elle convie l'un de ses chevaliers et lui demande de baisser ses chausses pour qu'elle puisse extraire un peu de sperme pour en assaisonner son plat.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 4
  },
  {
    nom: "Le prélèvement manuel",
    id: 33,
    pitch: "{prenom} est préleveuse dans une clinique qui s'occupe de la fertilité. Le patient regarde un film porno assis sur un fauteuil tandis qu'elle doit s'occuper d'extraire son sperme. Elle reste habillée, très professionnelle, et ses gestes n'ont rien de sensuels, elle doit juste prélever sa semence dans ce récipient, à la force du poignet ou de ses lèvres.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La démonstration anatomique",
    id: 34,
    pitch: "{prenom} est professeure à la fac de biologie. La session de ce soir est très particulière, puisqu'elle va utiliser un cobaye pour montrer à ses élèves l'anatomie masculine ainsi que son orgasme. Pour cela, il se mettra à quatre pattes, cul tourné vers les apprentis, et elle détaillera les différentes parties de son appareil génital, puis passera à la pratique. Elle lui caressera la bite, passera sa langue sur ses couilles, tétera un peu son gland, et surtout le branlera comme on trait une vache jusqu'à le faire éjaculer sur le bureau.",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 3,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La terrible vision",
    id: 35,
    pitch: "Ce n'est pas la première vision de {prenom}, mais c'est la plus terrifiante. Elle sait que si ce type qu'elle n'a jamais vu sort de cette pièce, l'enchainement des circonstances entrainera le monde à sa perte. Elle doit absolument le retenir un peu. Suffisamment longtemps pour que cette vision cesse de la hanter. Elle fera tout pour l'empêcher de partir. Quitte à donner d'elle-même. Il ne devrait pas resister à la vue de ses seins, même s'il ne la connait pas. Et si ça ne marche pas, quel homme refuse de se faire tailler une pipe ? Et de jouir sur ses gros seins ?",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "L'entraineuse d'IA",
    id: 36,
    pitch: "{prenom} a un travail bien atypique. Elle doit effectuer des séances sexuelles dans le but de capter toutes les sensations masculines qui permettront d'entrainer une IA. L'homme devant elle est bardé de capteurs. Elle pense l'avoir déjà vu lors d'une précédente séance. Un parmi un autre, elle en voit tellement. Aujourd'hui, elle doit juste offrir sa bouche au cobaye pour qu'il la lui baise jusqu'à éjaculation. Elle est libre de participer activement ou non.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La créatrice de cyborgs",
    id: 37,
    pitch: "{prenom} est une inventrice extraordinaire. Sa dernière idée : un cyborg plus vrai que nature. Son problème : elle n'a que très peu fréquenté d'humains, encore moins d'hommes. Elle a perfectionné son modèle au mieux qu'elle pouvait, mais tout ce qui est organes génitaux n'est pas du tout au point. Elle embauche donc un homme, humain, pour découvrir avec lui les sensations qu'elle doit ajouter à son invention. Il lui faudra donc toucher sa bite, ses couilles, prendre des notes sur la texture du gland, le goût du pré-sperme et du sperme...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 2,
    minOral: 2,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La piqûre",
    id: 38,
    pitch: "{prenom} s'est faite piquer par une méduse à un endroit bien délicat. Problème, elle est seule sur cette plage et si la piqûre n'est pas traitée rapidement, cela risque de devenir dangereuse. Il y a bien cet inconnu, mais va-t-il accepter le remède qu'elle lit, effarée, sur internet ? Est-ce qu'il va être d'accord pour lui éjaculer sur l'endroit où elle s'est faite piquée, c'est à dire pile poil entre les deux fesses ? Il va falloir qu'elle soit très persuasive.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 1
  },
  {
    nom: "La chirurgienne scrupuleuse",
    id: 39,
    pitch: "{prenom} vient d'opérer ce patient d'une rare maladie des testicules. Par professionnalisme, elle aimerait vérifier le bon fonctionnement de son appareil génital. De manière parfaitement médicale, elle va donc l'inviter à s'installer sur sa table d'auscultation, les jambes repliées et écartées, puis lui prodiguer une masturbation et une fellation jusqu'à obtenir une éjaculation satisfaisante.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La riche veuve",
    id: 40,
    pitch: "{prenom} a perdu son mari beaucoup trop tôt. Elle n'a pas eu le temps d'avoir un enfant. Et ne veut pas se marier de nouveau. Alors elle se paye des prostitués en espérant trouver un géniteur adéquat. Elle en profite pour assouvir ses envies. Le procédé est toujours le même : le prostitué est allongé, nu. Elle le branle et le suce en même temps, en le regardant dans les yeux. De temps en temps, elle l'excite par ses mots crus. Jusqu'à ce qu'il jouisse dans sa bouche. Là elle recrache toute la semence sur le pénis encore dur, puis vient se frotter le clitoris dessus, tant pour s'imprégner de sperme que pour se faire jouir à son tour.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 5
  },
  {
    nom: "L'employée de maison docile",
    id: 41,
    pitch: "{prenom} obéit toujours à Madame. Elle veut toujours obtenir la plus grande satisfaction de sa maîtresse. Et aujourd'hui, elle lui ordonne d'obtenir le plaisir de monsieur. Apparemment, Madame n'a pas la tête à ça et lui délègue la tâche. {prenom} rejoint donc Monsieur dans son office et demande poliment à passer sous le bureau tandis qu'il travaille à ses choses importantes. Elle n'a pas souvent vu de pénis, aussi elle est un peu intimidée. Elle découvre de ses doigts, lèche un peu le gland, puis se met au travail.",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 2,
    minOral: 4,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La locataire en retard",
    id: 42,
    pitch: "{prenom} a du retard dans son loyer. Son proprio n'est pas content et la menace d'une procédure judiciaire. Elle va donc tout faire pour le convaincre de ne pas faire ça. Elle a remarqué qu'il regardait souvent ses gros seins, aussi lorsqu'elle se met à genoux pour l'implorer, elle fait glisser sa queue hors de son pantalon pour venir la remettre au chaud sous son t-shirt, entre ses nichons, à portée de bouche...",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La prostituée exigeante",
    id: 43,
    pitch: "{prenom} est une prostituée de luxe. Il faut payer cher pour passer du temps avec elle et elle est très regardante sur les pratiques. Elle ne touche pas aux couilles trop velues, elle ne lèche pas de cul, et surtout elle laisse le client jouir sur lui-même. Sauf si le client est plein aux as et arrive à sortir un nombre capable de lui faire changer d'avis. Cette fois, il aura droit de lui jouir sur son sublime visage.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La douce berceuse",
    id: 44,
    pitch: "{prenom} est gouvernante dans le domaine de Monsieur. C'est un homme seul et aux étranges habitudes. La journée, elle s'occupe de la maison, la nuit, elle s'occupe de lui. Et ce qu'il aime, c'est sa douce berceuse remplie de mots crus et salaces. Ce qu'il aime, c'est poser sa tête sur ses genoux et téter ses gros seins tandis qu'elle le branle et lui raconte toutes les cochonneries qui lui passent par la tête.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'apprentissage d'une novice",
    id: 45,
    pitch: "{prenom} a un précepteur. Ses parents le payent pour qu'il lui garantisse tout ce qu'une femme de la haute noblesse doit savoir, dans tous les domaines. Quand elle lui a demandé de lui apprendre à donner du plaisir aux hommes, il a d'abord refusé, mais a fini par reconnaitre que cela pouvait aussi faire partie de ses attributions, tant que ça restait entre eux deux. Il s'est donc assis sur le bord du lit et l'a donc invité à s'agenouiller pour qu'elle découvre l'anatomie masculine. Au début de ses mains maladroites, puis d'une langue timide, et enfin d'une bouche curieuse. Si elle veut voir à quoi ressemble la semence d'un homme, elle doit le faire jouir sur ses seins et en récupérer une goutte avec le doigt.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 2
  },
  {
    nom: "L'expérience culinaire",
    id: 46,
    pitch: "{prenom} a besoin de sperme pour sa nouvelle recette. C'est une idée novatrice qui pourrait fonctionner, elle en est sûre, mais ça demande une matière première plutôt difficile à obtenir en grande quantité. Depuis sa cuisine, elle appelle donc son commis et lui demande de se déshabiller et se mettre à quatre pattes au-dessus d'un récipient. Elle le trait sans douceur, comme une vache. Elle pense que pour obtenir un bon produit, elle doit s'occuper en même temps de ses couilles productrices en les caressant, les léchant et les suçant.",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La douche dorée",
    id: 47,
    pitch: "Alors que son copain est sous la douche, {prenom} la rejoint et lui avoue qu'elle a un fantasme inavouée : elle aimerait qu'il lui pisse dessus pendant qu'elle se caresse. Il est surpris, mais vu qu'ils sont sous la douche, il se laisse tenter. Elle se met à la hauteur qu'elle désire et lui indique où viser. Pendant se temps, elle se caresse. Si elle est d'humeur, elle peut aussi le sucer pour goutter un peu le fruit défendu et finir par le faire éjaculer.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La punition",
    id: 48,
    pitch: "{prenom} est punie. Elle ne dira pas à Monsieur qu'elle a fait exprès de faire tomber le vase en nettoyant la salle de reception. Elle ne dira pas à Monsieur qu'elle aime quand elle est assise sur ce fauteuil luxueux et qu'il déboutonne son pantalon pour sortir sa queue en prenant un ton sévère. Elle ne lui dira pas non plus qu'elle aime se sentir utilisée. Elle gardera pour elle qu'elle sait qu'il ne fait pas ça pour la punir mais pour son plaisir personnel. Elle se retiendra de sourire quand il frottera son sexe sur son visage. Elle se retiendra aussi de gémir lorsqu'il s'enfoncera entre ses lèvres. Mais quand la punition viendra, il sera si occupé à lui baiser la bouche pour se vider sur son front qu'il ne fera pas attention à ses doigts sur son clitoris.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "L'assistante à domicile",
    id: 49,
    pitch: "{prenom} rend visite à un patient spécial. D'ordinaire, elle doit s'occuper de soins tout à fait courants, mais ici ce n'est pas le cas. Il souffre d'une maladie qui requiert qu'il décharge quotidiennement. Au début, elle venait juste pour lui rappeler de le faire chaque jour, mais rapidement elle s'est rendue compte qu'il oubliait ou n'y parvenait pas. Aussi, elle a finit par assister à ses masturbations pour être certaine qu'il les effectuait. Et de fil en aiguille, elle s'est mise à l'aider plus directement. C'est ainsi qu'elle se retrouve aujourd'hui à le sucer et caresser ses couilles pour le faire jouir dans sa bouche.",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "Le pacte sacré",
    id: 50,
    pitch: "Tous les ans, un guerrier et une guerrière de chaque tribu doivent se lier par un pacte, dans un rituel tenu secret des sages. C'est le prix à payer pour éviter la guerre. {prenom} a été choisie pour sa tribu. Elle observe celui qui se liera avec elle par la semence. Elle soupire, mais elle doit le faire. Elle s'allonge à ses côtés, nue comme lui, tête bêche. Tous deux observent le sexe de l'autre. Lui commence à la caresser maladroitement, elle fait de même. Elle a bien écouté les sages et s'applique à sucer ce sexe dur pour en extraire la semence. Quand elle est dans sa bouche, elle se lève et embrasse son nouveau partenaire pour sceller le pacte.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 5
  },
  {
    nom: "La masseuse personnelle",
    id: 51,
    pitch: "{prenom} est une masseuse à domicile. Mais selon les tarifs indiqués, elle peut pratiquer différents types de massage. Ce client a payé un prix élevé, aussi elle va bien s'occuper de lui. Elle va commencer par le masser partout, sur tout le corps, mais elle sait d'expérience que le client n'a envie que d'une chose : qu'elle se concentre entre ses jambes. Nue, elle va se frotter à lui, lui cajoler sa petite queue toute dure, ses petites boules bien pleines qui roulent sous sa langue, ce gros gland gonflé qui sursaute quand elle y passe les lèvres. Elle va y aller doucement, tout en suçotages et léchages. Elle ne fait jamais rentrer de pénis en elle, dans aucun de ses orifices, c'est la seule règle qu'elle s'est fixée. Mais il en aura pour son argent et elle continuera à le masser avec son propre sperme quand il aura bien joui.",
    minPresentation: 4,
    minCaresses: 2,
    minExploration: 3,
    minOral: 2,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La préparatrice de compétitions",
    id: 52,
    pitch: "{prenom} est préparatrice sportive. Un des joueurs de l'équipe qu'elle suit a l'air d'accuser moralement le coup. Elle sait comment obtenir de lui ses meilleures performances : un bon massage et il va faire des miracles. Un massage génitale, bien sûr, avec ses mains, ses lèvres, sa bouche, jusqu'à ce qu'il se relâche sur sa langue. C'est de loin la meilleure méthode !",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La secrétaire prévenante",
    id: 53,
    pitch: "{prenom} sait exactement ce dont son patron a besoin avant de commencer cette journée qui s'annonce éprouvante. Très sexy dans son petit tailleur cintré, lunettes sur le nez, cheveux attachés, elle passe sous le bureau sans un mot. Il ne la regarde même pas. À peine gémit-il lorsqu'elle sort sa queue et commence à la caresser. Elle masse bien ses couilles et tète doucement son gland. Elle parle pour deux, l'encourageant des mots et de la langue à jouir sur son visage de salope.",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La parente d'élève investie",
    id: 54,
    pitch: "{prenom} veut absolument que son fils ait les meilleures notes à l'école. Et pour cela, elle est prête à s'investir à fond. C'est pourquoi elle a demandé un entretien avec le professeur qui ne comprends pas bien ce qu'elle attend de lui, vu que son fils est au CP. Mais {prenom} insiste tant qu'elle finit à genoux devant lui, les seins autour de sa queue qu'elle tète goulûment. Elle le masturbe avec détermination en faisant monter et descendre ses nichons le long du membre dur, jusqu'à ce qu'il recouvre sa gorge et sa poitrine.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La botaniste de l'extrême",
    id: 55,
    pitch: "{prenom} a découvert une nouvelle plante dans la forêt amazonienne. Après l'avoir étudiée, elle pense qu'elle vient d'inventer le plus puissant aphrodiaque naturel existant. Pour vérifier son efficacité, elle choisit un de ses collègues, mignon mais timide. Elle lui fait boire sa potion en lui disant qu'il allait avoir une surprise. Quelques minutes plus tard, il s'est déjà mis nu et est prêt à lui sauter dessus. Elle le réfrenne : son but est de voir à quel point le produit le rend plus docile. Elle lui demande donc de se mettre sur le dos, les jambes pliées et relevées au maximum pour qu'elle puisse avoir accès à sa queue, ses couilles et son anus. Elle va s'amuser avec tout ça jusqu'à le faire jouir et le barbouiller de son propre sperme.",
    minPresentation: 1,
    minCaresses: 5,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 5
  },
  {
    nom: "La servante dévouée",
    id: 56,
    pitch: "{prenom} n'a qu'un seul rôle : obéir au maître des lieux. Que soit pour nettoyer ses appartements ou lorsqu'il a besoin de se vider. Ce soir-là, elle est agenouillée entre ses jambes, il la tient par les cheveux et lui baise la bouche sans tendresse. Elle bave abondemment, mais attend patiemment qu'il soit proche de la fin pour se retirer adroitement.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La répétition",
    id: 57,
    pitch: "{prenom} a peut-être un peu exagéré, mais c'est tellement bon. Elle a un crush sur son meilleur ami et a inventé un prétexte pour le baiser. Elle est comédienne et elle lui a expliqué qu'elle devait répéter une scène de sexe sur un prochain tournage et qu'elle aimerait bien s'entrainer avec lui d'abord, si il le voulait bien. Il a un peu rechigné, mais il s'est vite retrouvé avec la chatte de son amie sur le nez et sa queue entre ses lèvres. Elle lui a dit qu'elle devait jouer une femme très excitée, aussi elle n'a pas eu beaucoup à simuler tant elle est trempée. Elle se frotte sur sa bouche comme si c'est la dernière fois qu'ils se voient et le suce avec gourmandise. Quand il jouit dans sa bouche, elle recrache tout pour recouvrir son sexe et l'observer avec un petit sourire coquin.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 2,
    minOral: 3,
    minEjaculation: 4,
    minSperme: 2
  },
  {
    nom: "La courtisane renommée",
    id: 58,
    pitch: "{prenom} est une courtisane très respectée à la cour de l'empereur. Mais la nuit venue, elle devient une redoutable espionne usant de ses charmes et de son expertise dans les relations charnelles. Le dignitaire qui est ce soir-là face à elle n'est pas prêt à lui révéler ses secrets, mais elle est patiente et persévérante. Elle caresse doucement l'homme sur ses lourdes couilles, les soulève, les masse, puis ses doigts dessinent de petits rond un peu plus bas, à la base du périnée. Elle se glisse entre ses jambes pour continuer son oeuvre avec sa langue, alternant la base de la queue, les boules et le pli de peau sensible. Le final est toujours efficace : d'une bouche avide et baveuse, elle pompe le membre tendu qu'elle branle d'une main et masse en-dessous de l'autre.",
    minPresentation: 1,
    minCaresses: 3,
    minExploration: 4,
    minOral: 4,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La directrice d'école autoritaire",
    id: 59,
    pitch: "{prenom} n'est pas contente du tout de son surveillant. Il a laissé les choses s'envenimer et elles ont prises une tournure très désagréable. Il doit être puni. Ils connaissent tous la sentence. Personne n'y échappe, il ne fera pas exception. Elle est en petite tenue, jamais nue, ils ne méritent pas cette vision. Lui, par contre, est nu comme un ver et allongée sur ses genoux, le cul tourné vers le ciel. Il a les bras croisés sous sa tête et attend sa punition. Elle prend plaisir à alterner caresses et fessées, à le branler, à le serrer, à masser ses couilles puis le pincer. Elle se caresse quand elle enfonce un doigt dans son cul. S'il jouit, elle le fait juter sur ses cuisses et sa chatte pour se branler avec.",
    minPresentation: 2,
    minCaresses: 5,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La concubine dévouée",
    id: 60,
    pitch: "{prenom} est la quatrième concubine du Roi. Les trois premières ayant échoué à lui donner un héritier, c'est à son tour de le combler. Elle applique les leçons apprises à l'académie des plaisirs. D'abord l'exciter en se déshabillant sensuellement. Ensuite l'aguicher en le caressant de ses seins, de ses mains. Le rendre dur en lui faisant sentir son humidité, du nez et de la bouche. Le tendre encore en lui caressant le sexe d'une main douce. Puis le sucer, tendrement, lentement, en le regardant dans les yeux. Le faire monter avec des mots crus. Lui expliquer comment la semence royale doit couler en elle et la manière dont elle va s'y prendre. Le faire jouir.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 1
  },
  {
    nom: "La stagiaire ingénue",
    id: 61,
    pitch: "Quand son maître de stage lui a proposé d'expérimenter sur leur propre corps, {prenom} n'a pas bronché, persuadée que c'était une étape importante de son apprentissage. C'est ainsi qu'elle a appris à le masturber et découvert l'intensité d'un cunnilingus. Cette fois, la leçon portait sur \"faire l'amour à sa bouche\". Elle était curieuse, il était ravi. Elle fut donc installée nue, allongée, et vit arriver le pénis de son tuteur droit sur sa bouche qu'elle ouvrit consciencieusement.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La jeune fille au pair",
    id: 62,
    pitch: "{prenom} ne comprend pas bien le français. Depuis qu'elle est arrivée en France, elle a progressé, mais elle a des lacunes dans une certaine partie du vocabulaire qui l'intéresse : tout ce qui a trait à la sexualité. Elle a demandé conseil à la maîtresse de maison qui lui a proposé d'obtenir un cours particulier auprès de son mari, ce que ce dernier accepte sans hésiter. C'est ainsi qu'elle se retrouve entre ses jambes à observer avec curiosité - et un peu de naïveté - l'appareil génital masculin. Elle compte bien tout connaitre du vocabulaire et pour cela n'hésite pas à donner un coup de main et de langue. S'il faut lui lécher les couilles pour en apprendre plus, elle le fera. S'il faut goûter son sperme aussi...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 2,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 2
  },
  {
    nom: "L'apprentie masseuse",
    id: 63,
    pitch: "{prenom} veut tester sur son mari les différentes méthodes et points de pression érotiques qu'elle a apprise dans ses cours de massage. Pendant qu'elle le caresse, le masturbe, tourne autour de ses couilles et de son anus, elle va lui raconter innocemment sur combien d'hommes différents elle a pratiqué durant son stage. Est-ce que lui aussi, il va lui jouir sur ses habits sans prévenir ?",
    minPresentation: 2,
    minCaresses: 4,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'actrice amatrice",
    id: 64,
    pitch: "Dans le prochain film qu'elle va tourner, {prenom} a une scène de fellation qui l'inquiète. Elle n'a pas suffisamment pratiqué et c'est la première fois qu'elle tourne une scène de sexe. Elle demande à un ami de l'aider à se préparer. Elle se mettra seins nus pour ne pas se tâcher et prendra le temps qu'il faut pour apprendre à s'enfoncer la queue tendue le plus profondement possible. Quand il lui demandera s'il peut jouir, elle lui expliquera que ce n'est pas prévu au scénario mais que vu la situation, elle comprendrait que ça finisse par arriver...",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 2,
    minOral: 4,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "La prêtresse novice",
    id: 65,
    pitch: "{prenom} galère à réaliser le rituel sacré des Déesses du Plaisir qui lui permettrait d'obtenir le grade de Grande Prêtresse. Mais aujourd'hui est le bon jour et son cobaye le donneur parfait. Ce qu'il faut pour réussir, c'est prendre son temps, être patiente, faire monter la sauce au fond de ses bourses, l'exciter avec son corps et ses seins, le sucer avec délectation et en bavant abondemment, jusqu'à obtenir sa semence et se recouvrir le corps et le sexe avec.",
    minPresentation: 4,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 3,
    minSperme: 3
  },
  {
    nom: "La nouvelle au club de lecture érotique",
    id: 66,
    pitch: "{prenom} vient par curiosité, ne pensant pas que les textes seraient si explicites. Chaque lecture la fait rougir, mais elle pose des questions très sérieuses, si bien que l'un des lecteurs lui propose une approche plus pédagogique. Timidement, elle demande alors à ce qu'il lui explique des termes et des pratiques comme : couilles, fellation, suçage de boules, gorge profonde, éjaculation faciale...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 3,
    minOral: 4,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La fée égarée",
    id: 67,
    pitch: "{prenom} s'est perdue dans le monde des humains. Curieuse, elle les espionne pour les comprendre. Elle les trouve fascinant. Surtout ceux qui ont un truc qui pend entre les jambes quand ils sont tout nus. Là, elle en a repéré un qui tire dessus tous les soirs, seul dans le noir. Elle veut comprendre, elle se faufile par la fenêtre et le fait sursauter. Elle lui explique la situation. Vu comme il la regarde, il est très vite convaincu de lui fournir une éducation basique sur les plaisirs du sexe. Surtout le sien. Il lui explique comment le branler, le sucer, le faire jouir sur ces gros seins et bien nettoyer sa queue avec la langue à la fin.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 2,
    minSperme: 3
  },
  {
    nom: "La bonne épouse",
    id: 68,
    pitch: "Quand son mari rentre, {prenom} sait ce qu'elle doit faire. Il s'installe dans son fauteuil et elle lui apporte son verre de vin. Une fois bu, elle lui tend le journal qu'il lit sans un mot. Elle pose un coussin au pied du fauteuil, s'y installe à genoux, écarte les jambes de son mari et lui déboutonne le pantalon. Elle sort son pénis et commence à le masturber doucement. Il ne lui a dit qu'une fois, mais elle fait attention à bien respecter ses désirs. Les premières minutes sont lentes, elle ne doit pas le prendre en bouche mais se contenter de le lécher longuement, partout, chaque morceau de peau, plusieurs fois. Une fois qu'il est prêt, il pose son journal. Et là, elle n'a plus rien à faire si ce n'est se pencher et ouvrir grand la bouche pour qu'il la lui baise et se vide en elle.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 4,
    minSperme: 1
  },
  {
    nom: "La nouvelle domestique",
    id: 69,
    pitch: "{prenom} prend ses nouvelles fonctions dans l'immense manoir. Monsieur a exigé une tenue très légère comme vêtements de fonction. Quand elle se rend le premier jour dans la chambre de Monsieur, elle ne s'attendait pas à le trouver dans le plus simple appareil sur son lit. Ni à ce qu'il commence à se caresser en l'observant faire le ménage. Il lui demande de se tourner, de se pencher, de se mettre à quatre pattes, et bizarrement, elle obéit. Quand il lui demande de s'approcher et de frotter ses fesses quasi nues à son pénis, elle obéit. Quand il lui demande de faire sa toilette, et surtout de nettoyer son sexe, elle obéit. Quand il lui dit de continuer le nettoyage avec la langue, elle obéit. Et quand il jouit et qu'il lui demande de nettoyer encore, elle obéit.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 3
  },
  {
    nom: "Le dilemme de la directrice",
    id: 70,
    pitch: "{prenom} a trouvé une technique très efficace pour faire gagner de l'argent à son patron. En temps que directrice des ressources humaines, elle propose aux employés mâles qui ne lui déplaisent pas trop, de troquer leur augmentation annuelle contre une demi-heure de sa propre soumission. Elle est plutôt canon, dans son petit tailleur, derrière ses lunettes de cochonne, aussi beaucoup acceptent et elle se soumet à leur désir. Celui du jour s'est approché d'elle, lui a demandé de se mettre à genoux, d'ouvrir la bouche et il lui baise en l'agrippant par les cheveux. Il répète sans cesse qu'il va finir sur son visage de bourgeoise et qu'il en aura pour son argent...",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "Le défi entre amies",
    id: 71,
    pitch: "Il y a un défi entre {prenom} et ses copines qui tournent depuis des mois : qui arrivera à le faire bander et encore mieux, le faire jouir ? Il parle sans cesse de ses problèmes sexuels et elles ont toutes envie de relever ce défi. Certaines s'y sont déjà cassés les dents, manière de parler... {prenom} profite qu'il soit resté après la soirée, devant son match de basket, pour se glisser près de lui sur le canapé. Sans un mot, elle déboutonne son pantalon. Il la regarde avec étonnement et elle lui fait un clin d'oeil. Elle sort le paquet tout mou, il hausse les épaules. Elle s'évertue à sucer l'escargot enroulé et ses deux petites coquilles bien rondes. Miracle, il prend de l'envol, {prenom} est très fière d'elle. Reste plus qu'à aller jusqu'au bout, ce qu'elle compte bien faire. Cela prendra le temps qu'il faudra, mais elle sera la première à faire couler son sperme entre ses lèvres...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 3,
    minOral: 3,
    minEjaculation: 1,
    minSperme: 3
  },
  {
    nom: "La curiosité prostatique",
    id: 72,
    pitch: "{prenom} l'assure à son mec : il va forcément adorer. Après avoir longuement hésité, il s'est donc mis à quatre pattes entièrement nu, le cul tourné vers sa copine. Après lui avoir bien caressé les fesses, les couilles et la queue, elle va ajouter à sa masturbation un petit doigt fureteur autour de son anus, puis qui va doucement s'y introduire et chercher la fameuse prostate. Normalement, il devrait jouir rapidement...",
    minPresentation: 1,
    minCaresses: 5,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La testeuse de stimulation",
    id: 73,
    pitch: "Lorsqu'elle a accepté ce boulot, {prenom} l'avait fait pour la science et la soif de découvertes. Elle ne se doutait pas qu'elle allait aussi devoir tester ses produits elle-même. Et sur ses collègues, qui plus est. Elle a accepté à la condition qu'elle porte un masque et elle a choisit le protocole pour être certaine qu'il ne voit pas son visage. Surtout qu'elle le croise tous les jours, lui, ce serait trop gênant. Le produit à tester aujourd'hui est un amplificateur de sensations pour homme, il est censé décupler le plaisir autour de la zone périnéale. Elle est nue, allongée, et il est invité à se placer à poil aussi, un genoux de chaque côté de ses oreilles, la queue orientée vers le ventre. Elle est chargée de le masturber tout en léchant les zones d'intérêt : la hampe, les couilles et le périnée. C'est très perturbant de faire ça sur un collègue qui ne se doute de rien. Elle commence à apprécier et visiblement lui aussi. Elle a hâte de mesurer la force de son éjaculation...",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 4,
    minOral: 2,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "Le préparatrice en cosmétique",
    id: 74,
    pitch: "{prenom} doit obtenir la meilleure fragrance possible. Pour cela, elle a utilisé plein de protocoles expérimentaux possibles et elle a acquis une certaine expérience. Malheureusement, il n'est pas facile de trouver le donneur adéquat. Elle convoque donc plein d'hommes dont elle demande à cacher le visage, elle s'en moque, elle veut juste leur semence. Quand ils s'allongent, elle les fait se glisser entièrement sous un drap, de sorte à ne faire sortir que leur queue qu'elle surélève d'un ou plusieurs coussins. Elle doit pouvoir accéder facilement à l'entièreté de leur entrejambe. Là, le secret n'est pas dans la fellation, mais au contraire dans une très lente masturbation agrémentée d'une attention particulière sur la production de sperme. Il faut lécher les couilles, la zone en dessous, serrer le scrotum, sucer baveusement les deux boules lourdes. Quand une goutte de présperme se forme au bord du méat, elle y goutte avec plaisir pour en découvrir les délices. Si cela répond à ses attentes, alors elle ne jette pas son cobaye immédiatement et va jusqu'au bout pour obtenir sa jouissance.",
    minPresentation: 1,
    minCaresses: 3,
    minExploration: 4,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 2
  },
  {
    nom: "La coach personnelle",
    id: 75,
    pitch: "{prenom} est coach personnelle d'un riche homme d'affaires. Elle intervient sur tous les plans de sa vie, lui proposant des méthodes et des approches nouvelles qui lui permettent d'être plus efficace en tout domaine. Elle lui a même proposé d'utiliser ses méthodes sur sa vie sexuelle. La question du jour : quelle est la meilleure méthode pour le masturber ? {prenom} découvre le sexe de son patron en déglutissant, mais elle garde bonne figure, c'est une professionnelle. Et elle essaie alors de trouver la meilleure approche, lui demandant à chaque fois de noter ses remarques. Elle essaie donc avec les mains, classique. Avec la bouche, ses lèvres montant et descendant des couilles jusqu'au gland, comme pour mimer une masturbation, en serrant doucement parfois avec les dents. Avec les seins, qu'elle a volumineux. Avec les pieds aussi, beaucoup plus atypique. Avec la chatte, enfin. Elle se frotte sur son patron l'air de rien, mais elle ne peut pas longtemps cacher son excitation...",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 1
  },
  {
    nom: "La technicienne en orbite",
    id: 76,
    pitch: "{prenom} enfile sa combinaison et rejoint l'astronaute en chef pour les séances d'essais. Ce sont les seules séances qui sont filmés pour analyses complémentaires. Il s'agit d'étudier les rapports sexuels en orbite. Ce qui est bien avec ces tests, c'est qu'ils sont variés, tant en terme de protocoles que de partenaires. Elle a participé avec tous les astronautes qui semblaient ravis de ses compétences. Elle a déjà testé la pénétration vaginale, anale, la fellation, le cunnilingus, et plein d'autres choses très amusantes qu'elle connaissait à peine avant d'arriver sur la station. Cette fois, ils parlent d'éjaculation faciale. Elle voit à peu près le principe et s'installe sur le fauteuil tandis qu'il s'approche, la queue à la main. Elle ne l'a pas encore sucé, lui, elle va encore bien s'amuser...",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La guide touristique acharnée",
    id: 77,
    pitch: "Lors d’une visite privée dans un château isolé, {prenom} découvre que son unique client est un critique très influent et qu'il pourrait littéralement changer le cours de sa carrière de guide touristique. Elle va alors démontrer l'étendue de son savoir et de sa motivation. Mais face à sa moue dubitative, elle va sortir les grands moyens. Dans sa tête, les grands moyens, ça voulait dire de se mettre à genoux face à lui, sortir sa queue, la branler entre ses seins, la pomper avidemment et la faire cracher sur son visage. Elle verra bien s'il a la même conception de la chose...",
    minPresentation: 1,
    minCaresses: 2,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La passagère clandestine",
    id: 78,
    pitch: "{prenom} s’est introduite à bord clandestinement. Mais le capitaine la découverte. Il compte la laisser au prochain port, à moins qu'elle veuille bien agrémenter son voyage en restant avec lui le soir dans sa cabine. Au début, il lui a demandé de lui montrer ses seins, ce qui l'amusait. Elle jouait de ses attraits avec humour. Les jours passant, il augmentait ses demandes à chaque port. Désormais, le rituel était bien huilé, comme la queue qu'elle suçait en l'enfonçant profondément tandis qu'il se tenait assis sur sa couchette, un verre à la main. Il la regardait s'acharner à le faire jouir avec un petit sourire satisfait. Son plaisir était comblé lorsqu'elle léchait d'une langue taquine le sperme qui coulait sur ses seins.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 4,
    minEjaculation: 2,
    minSperme: 2
  },
  {
    nom: "La soirée arrosée entre collègues",
    id: 79,
    pitch: "La soirée est bien avancée et un jeu a été proposé. Il s'agit pour {prenom} de deviner qui est le collègue sous le drap dont seule la queue dépasse. Elle doit deviner parmi la vingtaine présente qui est dissimulé. Elle n'a pas le droit de soulever les linges, uniquement de toucher le sexe qui se présente à elle. Au mieux, elle peut espérer faire gémir le partenaire inconnu pour obtenir des indices sonores. Chaque fois qu'elle pense avoir une idée, elle propose un nom et s'il n'y a pas de réponse, c'est que c'est un echec, et {prenom} se remet au turbin, essayant de la bouche et des mains d'obtenir des indices.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 1,
    minOral: 2,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'oracle de la fertilité",
    id: 80,
    pitch: "Un couple est venu voir {prenom} pour ses dons de divination. La femme est inquiète, elle n'arrive pas à obtenir d'enfant. L'oracle a besoin de lire dans le sperme pour cela. Devant la femme, elle va donc branler et sucer son homme jusqu'à le faire jouir dans une assiette et lire les dessins ainsi formés. Elle y léchera quelques traits pour compléter sa lecture.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 2
  },
  {
    nom: "La camgirl en détresse",
    id: 81,
    pitch: "{prenom} est en panique. Elle avait plannifié un show en direct devant ses abonnés ce soir, mais elle vient de larguer son mec. C'est un con. Elle se console auprès d'un couple de bons amis, et raconte qu'elle risque de perdre beaucoup d'argent. Sa meilleure amie lui propose alors de faire la scène avec son propre mec. Celui-ci, bizarrement, n'est pas opposé à l'idée. {prenom} râle un peu quand elle découvre sa queue tendue : elle est bien plus longue que celle de son ex et pour la scène prévue, il la faut au repos. Il va donc se soulager avant et revient, mou. Elle s'allonge sur le lit, la tête à moitié dans le vide, et il s'approche d'elle, queue centrée sur la caméra. Après une présentation de la camgirl, celle-ci commence à lécher doucement le gland, la hampe, les boules, tout en douceur et en lenteur, pendant de longues minutes. Elle ne le sucera pas, mais continuera à le lécher tout en le branlant, jusqu'à obtenir une belle éjaculation sur sa bouche et ses joues.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 3,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "La prof d'espagnol perfectionniste",
    id: 82,
    pitch: "{prenom} aime beaucoup son nouvel élève. Si bien que, sans qu'elle ne s'en rende vraiment compte, elle le drague et l'aguiche. Elle s'habille souvent très sexy, lui donne des mots de vocabulaire précis, comme \"décolleté\" ou \"langoureux\". Il ne dit rien et reste très concentré sur ses notes. Lorsqu'elle lui propose de lui décrire le vocabulaire du corps humain, il commence enfin à rougir. {prenom} fait semblant de rester très professionnelle quand elle retire ses sous-vêtements pour lui expliquer par l'exemple comment on dit \"téton\" en espagnol ou \"clitoris\". Lors de sa dernière leçon, elle ne veut pas le laisser partir sans une séance mémorable, aussi elle lui propose de passer à l'anatomie masculine. Une fois à poil, sa sublime prof entre ses jambes, il ne peut plus dissimuler son trouble et sa queue durcit rapidement sous les doigts faussement scolaires. Elle donne alors des explications précises sur le sexe masculin, puis sur les termes qui entourent la masturbation et la fellation...",
    minPresentation: 2,
    minCaresses: 2,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "L'étrange deal",
    id: 83,
    pitch: "{prenom} est un peu en manque de sexe. Mais elle en a marre de ne tomber que sur des tocards. Après avoir demandé conseil à sa meilleure amie, celle-ci lui propose une solution plutôt peu commune, avec l'accord de son mec. Ce dernier, ne voulant pas tromper sa copine, va prendre un cachet de somnifère et laisser son corps à la disposition de {prenom} qui pourra en faire ce qu'elle veut. C'est donc avec un peu d'appréhension, mais aussi beaucoup d'excitation, qu'elle commence à lui prendre la main pour la passer sur son corps nu, se caresser avec. Elle fait de même avec sa bouche endormie. Elle manque de jouir en se frottant sur ses lèvres de beau barbu, mais se retient pour s'occuper de la queue qu'elle devine grossir sous le drap. Elle a trop envie de tester ses fantasmes, dont celui de partager sa semence avec un homme...",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 5
  },
  {
    nom: "Le leçon de l'instructeur",
    id: 84,
    pitch: "Il lui a tout appris : le combat à l'épée, l'étiquette, le déchiffrage de certains codes militaires, l'infiltration, tout. {prenom} a une confiance aveugle en son instructeur. Le roi, son père, lui a confié son éducation et il fait ça très bien. Une grande complicité est née entre eux deux. Si bien que, quand il lui propose de lui apprendre à faire une masturbation, elle est tout aussi partante que s'il lui proposait de monter à dos de tigre. Comme à son habitude, il va prendre le temps de lui expliquer chaque détail, chaque manipulation. Elle découvre la queue de son instructeur avec un peu de rose aux joues et se sent plus intimidée qu'avec une épée à la main, mais elle écoute ses instructions avec application. Surtout qu'il lui a bien expliqué que le but était qu'il y prenne du plaisir...",
    minPresentation: 4,
    minCaresses: 2,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 1
  },
  {
    nom: "La journaliste infiltrée",
    id: 85,
    pitch: "Quand {prenom} s'est infitrée dans le camp de ce candidat à la présidentielle, elle ne s'imaginait pas finir sous son bureau. Mais pour faire un bon article, il faut y mettre du sien. Aussi, quand elle a vu l'occasion de s'immiscer davantage dans son intimité, elle a foncé. Au début, c'était juste des jeux de séduction. Elle écartait ses jambes par inadvertance, lui dévoilant ses dessous. Ensuite, il n'y avait plus de dessous. Et là, tout s'est emballée et c'est elle qui a fini dessous. C'est le meilleur spot pour obtenir des informations. Elle l'entend discuter avec ses collaborateurs tandis qu'elle le masturbe lentement. Elle espionne ses coups de fil avec sa queue entre les lèvres. Elle récupère des secrets de campagne le visage plein de sperme.",
    minPresentation: 2,
    minCaresses: 1,
    minExploration: 2,
    minOral: 1,
    minEjaculation: 5,
    minSperme: 1
  },
  {
    nom: "L'hypnotiseuse",
    id: 86,
    pitch: "{prenom} est une spécialiste dans son domaine. Elle a réglé bon nombre de troubles chez ses patients et son expertise est reconnue internationalement. Pourtant, elle n'a jamais eu cas aussi... étrange. Ce patient aimerait contenter les désirs sexuels de son épouse mais il n'arrive pas à y accéder. Il aimerait qu'elle l'aide à s'ouvrir à certaines pratiques. Sous hypnose, complètement nu, à quatre pattes, il se laissera doigter le cul délicatement. {prenom} n'a jamais fait ça jusque là, mais elle y prend un certain plaisir. Elle profite qu'il soit sous hypnose pour se caresser et sucer cette belle queue pendue. Elle espère bien le faire jouir dans un verre et lui faire goûter sa propre semence. Ou peut-être qu'elle le fera éjaculer sur elle, qui sait...",
    minPresentation: 1,
    minCaresses: 5,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 1,
    minSperme: 5
  },
  {
    nom: "Le gage revanchard",
    id: 87,
    pitch: "Elle est très contente de sa revanche. Déjà, il lui avait lancé le gage de montrer ses seins à tous les amis présents. Plus tard dans la soirée, {prenom} avait dû montrer son cul et sa chatte. Elle était trop gênée, mais aussi terriblement excitée. Il le savait, il en jouait. Mais elle devait se venger. Alors quand les esprits se sont échauffés, quand quelques bites ont été tirées, elle a exigé de l'une d'elle de la pénétrée et de jouir en elle (simulé par votre partenaire), pour ensuite demander à son mec de lui bouffer la chatte et lui donner un orgasme devant tous ses potes.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 5
  },
  {
    nom: "La cheffe de projet motivante",
    id: 88,
    pitch: "{prenom} a promis à sa direction de terminer le projet ce soir. Aussi, quand tout les developpeurs sont partis, elle a commencé à paniquer. Tous ? Sauf un. Le meilleur. Elle le connait, il est capable d'en venir à bout dans la nuit. Elle se transforme donc en assistante particulière. Elle lui amène du café, à boire, lui commande à manger, et surtout l'aide à ne pas se distraire de son objectif. Quand elle remarque qu'il lance des coups d'oeil sur son décolleté, elle lui propose directement de se vider entre ses lèvres pour qu'il puisse revenir à sa tâche.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 4,
    minEjaculation: 4,
    minSperme: 4
  },
  {
    nom: "L'épouse dominatrice",
    id: 89,
    pitch: "Chaque soir, {prenom} rentre tard et attend de son mari qu'il se soit bien occupé de la maison. Elle dépose ses affaires dans ses bras qu'il s'empresse de ranger, puis lui sert son repas chaud, un bon verre de vin tandis qu'elle relate les affres de son travail fastidieux. Tout le long, il est à poil. Tout le long, il écoute et ne dit pas un mot. Quand elle a fini, elle désigne le sol. Il s'y allonge sur le dos, elle se lève, retire sa culotte, et s'accroupi au-dessus de sa bouche pour s'y frotter. Elle raconte alors à qui appartient la semence qu'il est en train de boire en même temps que de la faire jouir.",
    minPresentation: 1,
    minCaresses: 1,
    minExploration: 1,
    minOral: 1,
    minEjaculation: 3,
    minSperme: 5
  },
  {
    nom: "La coursière spéciale",
    id: 90,
    pitch: "{prenom} est coursière. Elle parcourt de longues distances pour passer un message envoyé par ses clients. Sauf que les messages qu'elle transmet sont agrémentés d'activités supplémentaires. Ce peut être un effeuillage, requis comme remerciement envers un artiste qui a pleinement tenu ses engagements. Ce peut être un tendre baiser pour une discussion romantique. Ce peut être une torride chevauchée pour un noble espiègle. Et ce peut être, comme aujourd'hui, la rondeur de ses seins et de ses lèvres sur la queue d'un acheteur hésitant.",
    minPresentation: 3,
    minCaresses: 1,
    minExploration: 1,
    minOral: 3,
    minEjaculation: 2,
    minSperme: 1
  },
  {
    nom: "Le couronnement de la princesse elfe",
    id: 91,
    pitch: "Aujourd'hui est un grand jour pour {prenom}, princesse elfe. Son couronnement est le début d'une grande ère de paix. Elle va enfin sceller cette alliance tant attendue entre son peuple et le royaume des humains, après des décennies de guerre et d'assassinats. Il ne s'agit pas d'un mariage d'amour, mais peut-être que cela pourrait finir par arriver... L'union doit se concrétiser dans la salle du trône, sur un lit transporté au centre de la pièce pour l'occasion. Douze témoins sont installés autour de la couche sacrée. {prenom} est nue, magnifique, d'une beauté féérique. Son futur époux n'est pas trop mal non plus, plutôt bien charpenté, des bras et de la queue. C'est elle qui sera dessus, comme pour le reste de son règne. Elle se glisse tête bêche et écrase sa chatte délicate sur la bouche de son allié, tandis que ses lèvres viennent gober le sexe tendu. L'alliance ne sera validé que lorsque les témoins pourront assurer que les deux ont joui. Il n'y a plus qu'à se mettre à l'ouvrage pour obtenir des cris et du sperme.",
    minPresentation: 5,
    minCaresses: 1,
    minExploration: 1,
    minOral: 5,
    minEjaculation: 4,
    minSperme: 1
  },
];
